### ISSUE TITLE
PHP errors using example.php / README code samples

### ISSUE THREAD

**Issue by pixelchutes** [messagemedia/messagemedia-php#4]
I am running into the following errors attempting to use the PHP examples provided in this repo.

**PHP 5.3.29**

```
PHP Fatal error:  Call to undefined method SoapFault::getResult() in messagemedia-php/example.php on line 74
```
This error was a result of a newly provisioned user with `Insufficient daily credit`. Took awhile to track this issue down, would have been helpful if the example code accounted for errors like these vs. logging the aforementioned SoapFault error.

```
PHP Warning:  Missing argument 3 for MMSoap::__construct(), called in readme-example.php on line 16 and defined in mmsoap/MMSoap.php on line 20
```

The second error was resolved by changing the sample in the `README.md` to:

```php
// Create new MMSoap class
$soap = new MMSoap($username, $password, array() ); // Added empty options array as 3rd param
```

**PHP 5.5.18**
```
Strict Standards: Declaration of MMSoapClient::__doRequest() should be compatible with SoapClient::__doRequest($request, $location, $action, $version, $one_way = NULL) in messagemedia-php/mmsoap/MMSoapClient.php on line 106
```

**Comment by dukevoo** [comment]
Thanks @pixelchutes, good idea on the error logging and the strict optional parameter in PHP 5.5, we'll update accordingly. Regarding the MMSoap creation, please note that the example.php does specify the options array line 43.

**Comment by pixelchutes** [comment]
Awesome, thanks @dukevoo. The example.php was solid. I was referring to the `README.md` sample code.

**Comment by dukevoo** [comment]
Cheers, we have a separate project on the way to consolidate and update README.md across our Github repos.

**Comment by kuldeep0103** [comment]
i am running the php sdk and i got error like this:

Strict standards: Declaration of MMSoapClient::__doRequest() should be compatible with SoapClient::__doRequest($request, $location, $action, $version, $one_way = NULL)

**Comment by kuldeep0103** [comment]
i am running the php sdk and i got error like this:
Strict standards: Declaration of MMSoapClient::__doRequest() should be compatible with SoapClient::__doRequest($request, $location, $action, $version, $one_way = NULL) in C:\wamp\www\messagemedia-php-master\mmsoap\MMSoapClient.php on line 106

**Comment by shawr** [comment]
The README, has been fixed, the following line need the options variable 
        // Set up stream context Server Name Indication (SNI) for use with proxy and HTTPS
    //$opts = array('ssl' => array('SNI_server_name' => $host,'SNI_enabled' => TRUE));
    //$context = stream_context_create($opts);

    // Set up SOAP Options
    $options = array( // Put options here to override defaults
            // Example Proxy Options

            //WsdlClass::WSDL_PROXY_HOST => '127.0.0.1',
            //WsdlClass::WSDL_PROXY_PORT => '8888'

            //WsdlClass::WSDL_PROXY_LOGIN => 'proxyUsername',
            //WsdlClass::WSDL_PROXY_PASSWORD => 'proxyPassword',
            //WsdlClass::WSDL_STREAM_CONTEXT => $context //If you require SNI
    );

    $soap = new MMSoap($username, $password, $options);
